#!/usr/bin/env python3
"""
Hiktaos CRECHE / NURSERY Report Card Generator.

Data source : creche.csv  (columns: #, Student, Number Work, Letter Work,
                            P.H.E, Health Habit, Rhymes)
              Each subject cell is "CA/Exam/Total" e.g. "20/30/50".
Template    : Hiktaos_Creche_Final.xlsx  (logo at xl/media/image1.jpeg)

Template score columns (rows 28-32 = the 5 subjects):
    G  = CA 1          (continuous assessment, part 1)
    H  = Assignment    (continuous assessment, part 2)
    J  = Examination
    L  = Total  -> formula =SUM(G,H,J)   (so Total == CA + Exam, always)
    N  = Grade (formula already in template)
    P  = Position in subject

Per the user's standing instruction ("take the first CA, split it into the two
CA boxes, and put the exam in the exam box"):
    G = round(CA / 2)
    H = CA - G
    J = Exam
The card's displayed Total is therefore CA + Exam (the formula truth).

The script preserves the embedded logo by copying the protected media/drawing
parts back over openpyxl's output (openpyxl drops images on save).
"""

import csv
import os
import re
import shutil
import zipfile

from openpyxl import load_workbook
from openpyxl.styles import Alignment, Border, Font, Side

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
BASE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(BASE, "Hiktaos_Creche_Final.xlsx")
DATA = os.path.join(BASE, "creche.csv")
OUT = os.path.join(BASE, "report_cards")
CLASS_FOLDER = "Creche"

CLASS_NAME = "Creche / Nursery"
NEXT_CLASS = "Nursery 1"

# subject column name in creche.csv  ->  report-card row number
SUBJECTS = [
    ("Number Work", 28),
    ("Letter Work", 29),
    ("P.H.E", 30),
    ("Health Habit", 31),
    ("Rhymes", 32),
]
N_SUBJECTS = len(SUBJECTS)

# Parts of the xlsx that openpyxl drops but must be preserved (logo + drawing).
PROT = [
    "xl/media/image1.jpeg",
    "xl/drawings/drawing1.xml",
    "xl/drawings/_rels/drawing1.xml.rels",
    "xl/worksheets/_rels/sheet1.xml.rels",
]

GRADE_TABLE = [
    (75, 100, "A1", "Excellent"),
    (70, 74, "B2", "Very Good"),
    (65, 69, "B3", "Good"),
    (60, 64, "C4", "Credit"),
    (55, 59, "C5", "Credit"),
    (50, 54, "C6", "Pass"),
    (45, 49, "D7", "Fair"),
    (40, 44, "E8", "Weak"),
    (0, 39, "F9", "Fail"),
]
GPA_MAP = {"A1": 4.0, "B2": 3.5, "B3": 3.0, "C4": 2.5,
           "C5": 2.0, "C6": 1.5, "D7": 1.0, "E8": 0.5, "F9": 0.0}

ORD = ["", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th",
       "10th", "11th", "12th", "13th", "14th", "15th", "16th", "17th", "18th"]

# Styles
THIN = Border(left=Side(style="thin"), right=Side(style="thin"),
              top=Side(style="thin"), bottom=Side(style="thin"))
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT = Alignment(horizontal="left", vertical="center", wrap_text=True)
F9 = Font(name="Arial", size=9)
F11B = Font(name="Arial", size=11, bold=True)
F12B = Font(name="Arial", size=12, bold=True)
F14G = Font(name="Arial", size=14, bold=True, color="006400")


def grade(t):
    t = max(0, min(100, t))
    for lo, hi, g, _ in GRADE_TABLE:
        if lo <= t <= hi:
            return g
    return "F9"


def ordinal(rank):
    return ORD[rank] if 1 <= rank < len(ORD) else str(rank)


def slug(name):
    return re.sub(r"[^\w]+", "_", name).strip("_")


# --------------------------------------------------------------------------- #
# 1. Read data
# --------------------------------------------------------------------------- #
def read_students():
    students = []
    with open(DATA, newline="") as f:
        for r in csv.DictReader(f):
            name = (r.get("Student") or "").strip()
            if not name or not name[0].isalpha():   # skip blank / "Generated by..."
                continue
            s = {"n": name, "subj": {}}
            for subj, _ in SUBJECTS:
                parts = (r.get(subj) or "").split("/")
                ca = int(parts[0]) if len(parts) > 0 and parts[0].isdigit() else 0
                ex = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 0
                # Card total is the formula =SUM(G,H,J) == CA + Exam.
                s["subj"][subj] = {"ca": ca, "ex": ex, "total": ca + ex}
            s["total"] = sum(v["total"] for v in s["subj"].values())
            students.append(s)
    return students


def rank_map(values_by_name):
    """Competition ranking (ties share a rank, next rank skips)."""
    order = sorted(values_by_name.items(), key=lambda kv: -kv[1])
    rk, prev, ri = {}, None, 0
    for i, (nm, v) in enumerate(order):
        if prev is not None and v < prev:
            ri = i
        rk[nm] = ri + 1
        prev = v
    return rk


# --------------------------------------------------------------------------- #
# 2. Save with logo preserved
# --------------------------------------------------------------------------- #
def save(path, modify):
    shutil.copy2(TEMPLATE, path)
    wb = load_workbook(path)
    modify(wb)
    tmp = path + ".tmp"
    wb.save(tmp)
    wb.close()
    with zipfile.ZipFile(tmp) as z:
        out = {n: z.read(n) for n in z.namelist()}
    with zipfile.ZipFile(TEMPLATE) as z:
        for n in PROT:
            if n in z.namelist():
                out[n] = z.read(n)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        for n in sorted(out):
            z.writestr(n, out[n])
    os.remove(tmp)


# --------------------------------------------------------------------------- #
# 3. Build one card
# --------------------------------------------------------------------------- #
def build_card(s, class_rank, subject_ranks, n_class):
    name = s["n"]
    path = os.path.join(OUT, CLASS_FOLDER, "Report_Card_%s.xlsx" % slug(name))

    total_marks = s["total"]
    avg = round(total_marks / N_SUBJECTS, 1)
    pct = round(total_marks / (N_SUBJECTS * 100) * 100, 2)
    overall = grade(round(pct))
    gpa = GPA_MAP.get(overall, 0.0)
    credit = sum(1 for v in s["subj"].values()
                 if grade(v["total"]) in ("A1", "B2", "B3", "C4", "C5", "C6"))
    pos = ordinal(class_rank)

    def mod(wb):
        ws = wb["Report Sheet"]

        # --- Student information ---
        ws["D16"].value = name
        ws["D16"].font = F12B
        ws["D16"].alignment = LEFT

        ws["D20"].value = CLASS_NAME
        ws["D20"].font = F12B
        ws["D20"].alignment = LEFT

        ws["M19"].value = n_class          # No. in Class
        ws["M19"].font = F12B
        ws["M19"].alignment = CENTER
        ws["M21"].value = n_class          # Total Pupils in Class
        ws["M21"].font = F12B
        ws["M21"].alignment = CENTER
        ws["M20"].value = pos              # Position in Class
        ws["M20"].font = F12B
        ws["M20"].alignment = CENTER

        # --- Subjects (rows 28-32) ---
        for subj, row in SUBJECTS:
            v = s["subj"][subj]
            ca, ex = v["ca"], v["ex"]
            g = round(ca / 2)
            h = ca - g
            ws.cell(row=row, column=7).value = g    # CA 1
            ws.cell(row=row, column=8).value = h    # Assignment
            ws.cell(row=row, column=10).value = ex  # Examination
            for c in (7, 8, 10):
                cell = ws.cell(row=row, column=c)
                cell.font = F9
                cell.alignment = CENTER
                cell.border = THIN
            # Position in subject
            sr = subject_ranks[subj].get(name, 0)
            ws.cell(row=row, column=16).value = ordinal(sr)
            ws.cell(row=row, column=16).font = F9
            ws.cell(row=row, column=16).alignment = CENTER
            ws.cell(row=row, column=16).border = THIN

        # --- Left summary block (rows 33-40, col G) ---
        summary = {
            33: total_marks,                       # TOTAL MARKS
            34: avg,                               # AVERAGE SCORE
            35: "%s%%" % pct,                      # PERCENTAGE (%)
            36: overall,                           # OVERALL GRADE
            37: pos,                               # POSITION IN CLASS
            38: n_class,                           # NUMBER IN CLASS
            39: credit,                            # CREDIT COUNT
            40: gpa,                               # GPA (4.0 SCALE)
        }
        for r, v in summary.items():
            ws.cell(row=r, column=7).value = v
            ws.cell(row=r, column=7).font = F11B

        # --- Right performance-summary box (rows 38-45, col X=24) ---
        for r, v in [(38, total_marks), (39, avg), (40, "%s%%" % pct),
                     (41, overall), (42, pos), (43, n_class),
                     (44, credit), (45, gpa)]:
            ws.cell(row=r, column=24).value = v
            ws.cell(row=r, column=24).font = F11B

        # --- Promotion + next class ---
        if ws["T60"].value == "PROMOTED":
            ws["T60"].value = "\u2714  PROMOTED"
            ws["T60"].font = F14G
            ws["T60"].alignment = CENTER
        ws["V64"].value = NEXT_CLASS
        ws["V64"].font = F12B
        ws["V64"].alignment = CENTER

    save(path, mod)
    return path


def main():
    os.makedirs(os.path.join(OUT, CLASS_FOLDER), exist_ok=True)
    students = read_students()
    if not students:
        print("No students found in creche.csv")
        return

    n_class = len(students)
    class_rank = rank_map({s["n"]: s["total"] for s in students})
    subject_ranks = {}
    for subj, _ in SUBJECTS:
        subject_ranks[subj] = rank_map(
            {s["n"]: s["subj"][subj]["total"] for s in students})

    # Order output by class position (1st first)
    students.sort(key=lambda s: -s["total"])

    print("\n\U0001F4DA Creche / Nursery  (%d students, %d subjects)"
          % (n_class, N_SUBJECTS))
    print("%-4s %-6s %-7s %s" % ("Pos", "Total", "Avg", "Student"))
    for s in students:
        print("%-4s %-6d %-7s %s" % (
            ordinal(class_rank[s["n"]]), s["total"],
            round(s["total"] / N_SUBJECTS, 1), s["n"]))
        build_card(s, class_rank[s["n"]], subject_ranks, n_class)
        print("        \u2705 %s" % s["n"])


if __name__ == "__main__":
    main()
